database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password:

  url: jdbc:mysql://localhost:3306/mtg_draft_leagues?useSSL=false

  properties:
      hibernate.show_sql: true
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: update

server:
  applicationConnectors:
    - type : http
      port : 9000
  adminConnectors:
    - type : http
      port : 9001

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG