database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password:

  url: jdbc:mysql://localhost:3306/mtg_draft_leagues?useSSL=false

server:
  applicationConnectors:
    - type : http
      port : 9000
  adminConnectors:
    - type : http
      port : 9001